name: CI/CD

on: 
  push:
    branches: 
      - '*'

jobs:
  build:

    name: CI/CD    
    runs-on: ubuntu-latest    
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Publish
      working-directory: src/BlazorFileSaver
      run: dotnet publish -c Release

    - name: Deploy to Test
      uses: netlify/actions/cli@master
      with:
        args: deploy --json -d src/BlazorFileSaver/bin/Release/netstandard2.0/publish/BlazorFileSaver/dist/
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    - name: Deploy to Production
      if: github.ref == 'refs/heads/master'
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod --json -d src/BlazorFileSaver/bin/Release/netstandard2.0/publish/BlazorFileSaver/dist/
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
